# Generated by Django 5.2.12 on 2026-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='usage',
            field=models.CharField(choices=[('horses', 'Horses'), ('mixed', 'Mixed Grazing'), ('rested', 'Rested'), ('hay', 'Hay'), ('other', 'Other')], default='horses', max_length=20),
        ),
    ]
