# Generated by Django 5.2.12 on 2026-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_location_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='expected_departure',
            field=models.DateField(blank=True, help_text='Anticipated departure date (for forecasting)', null=True),
        ),
    ]
