# Generated by Django 5.2.12 on 2026-04-04 13:47

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_placement_expected_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='dam_name',
            field=models.CharField(blank=True, help_text='Dam (mother) name', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg']), core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='horses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_file_size]),
        ),
    ]
