# Generated by Django 5.2.12 on 2026-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_horse_dam_name_alter_businesssettings_logo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('horse',), name='unique_active_placement_per_horse'),
        ),
    ]
