# Generated by Django 5.2.12 on 2026-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_enforce_unique_active_placement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'status'], name='invoice_owner_status'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['end_date'], name='placement_enddate_solo'),
        ),
    ]
