# Generated by Django 5.2.13 on 2026-04-30 07:53

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_dashboardpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
