# Generated by Django 5.2.13 on 2026-04-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_dashboardpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="next_run_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
