# Generated by Django 5.2.15 on 2026-06-11 15:17

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_businesssettings_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "heic",
                            "heif",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="horse",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="horses/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "heic",
                            "heif",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
