# Generated by Django 5.2.15 on 2026-06-13 21:26

import django.db.models.deletion
from django.db import migrations, models


def seed_initial_periods(apps, schema_editor):
    """Open one usage period per existing location from its current usage."""
    Location = apps.get_model("core", "Location")
    LocationUsagePeriod = apps.get_model("core", "LocationUsagePeriod")
    periods = [
        LocationUsagePeriod(
            location=loc,
            usage=loc.usage,
            start_date=loc.created_at.date(),
            end_date=None,
            source="auto",
            notes="Initial period (backfilled from current usage).",
        )
        for loc in Location.objects.all()
    ]
    LocationUsagePeriod.objects.bulk_create(periods)


def unseed(apps, schema_editor):
    apps.get_model("core", "LocationUsagePeriod").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_businesssettings_logo_alter_horse_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationUsagePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("horses", "Horses"),
                            ("mixed", "Mixed Grazing"),
                            ("rested", "Rested"),
                            ("hay", "Hay"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="manual",
                        help_text="Whether this period was logged manually or set automatically by a horse arrival/departure.",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_periods",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["location", "end_date"], name="usageperiod_loc_enddate"
                    ),
                    models.Index(
                        fields=["location", "start_date"],
                        name="usageperiod_loc_startdate",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("location",),
                        name="unique_open_usage_period_per_location",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_initial_periods, unseed),
    ]
