# Generated by Django 5.2.16 on 2026-07-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_locationusageperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="auto_generate_invoices",
            field=models.BooleanField(
                default=True,
                help_text="Automatically create draft invoices for the previous month on the 1st (drafts still need reviewing and sending)",
            ),
        ),
    ]
