# Generated by Django 5.2.16 on 2026-07-13 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_businesssettings_auto_generate_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="VAT percentage added to invoices: 0 if not VAT-registered, 20 for the UK standard rate. Applies to newly created invoices.",
                max_digits=4,
            ),
        ),
    ]
