# Generated by Django 5.2.16 on 2026-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="photo_thumb",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="horses/thumbs/"
            ),
        ),
    ]
