# Generated by Django 5.2.16 on 2026-07-13 14:32

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_horse_photo_thumb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HorsePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="horse_photos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "heic",
                                    "heif",
                                ]
                            ),
                            core.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="horse_photos/thumbs/%Y/%m/",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("condition", "Condition"),
                            ("markings", "Markings"),
                            ("injury", "Injury"),
                            ("arrival", "Arrival / check-in"),
                            ("other", "Other"),
                        ],
                        default="condition",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.horse",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_horse_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
