# Generated by Django 5.2.16 on 2026-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_viewer_restore_read_access"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(
                fields=["location", "end_date"], name="placement_loc_enddate"
            ),
        ),
    ]
