# Generated by Django 5.2.17 on 2026-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_placement_placement_loc_enddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived fields keep their history but are hidden from lists and pickers.",
            ),
        ),
    ]
