# Generated by Django 5.2.17 on 2026-09-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_location_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="usage",
            field=models.CharField(
                choices=[
                    ("horses", "Horses"),
                    ("mixed", "Mixed Grazing"),
                    ("rested", "Rested"),
                    ("hay", "Hay"),
                    ("arable", "Arable"),
                    ("other", "Other"),
                ],
                default="horses",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locationusageperiod",
            name="usage",
            field=models.CharField(
                choices=[
                    ("horses", "Horses"),
                    ("mixed", "Mixed Grazing"),
                    ("rested", "Rested"),
                    ("hay", "Hay"),
                    ("arable", "Arable"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
