# Generated by Django 5.2.17 on 2026-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_location_usage_arable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived locations keep their history but are hidden from lists and pickers.",
            ),
        ),
    ]
