# Generated by Django 5.2.17 on 2026-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_location_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardpreference",
            name="site",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
