# Generated by Django 5.2.17 on 2026-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_location_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Hidden from lists and pickers; every record is kept.",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the document type.",
                max_length=200,
            ),
        ),
    ]
