# Generated by Django 5.2.17 on 2026-09-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_owner_archive_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horsephoto",
            name="category",
            field=models.CharField(
                choices=[
                    ("condition", "Condition"),
                    ("markings", "Markings"),
                    ("injury", "Injury"),
                    ("arrival", "Arrival / check-in"),
                    ("foaling", "Foaling"),
                    ("other", "Other"),
                ],
                default="condition",
                max_length=20,
            ),
        ),
    ]
