# Generated by Django 5.2.17 on 2026-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_horsephoto_foaling_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("database_bytes", models.BigIntegerField(default=0)),
                ("media_bytes", models.BigIntegerField(default=0)),
                ("objects_pruned", models.PositiveIntegerField(default=0)),
                (
                    "keys",
                    models.TextField(blank=True, help_text="One object key per line."),
                ),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Backup run",
                "ordering": ["-started_at"],
            },
        ),
    ]
