# Generated by Django 5.2.17 on 2026-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_backuprun"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="microchip",
            field=models.CharField(
                blank=True,
                help_text="Microchip number, if the horse is chipped",
                max_length=50,
            ),
        ),
    ]
