# Generated by Django 5.2.12 on 2026-03-22 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('xero_tenant_id', models.CharField(blank=True, max_length=100)),
                ('xero_tenant_name', models.CharField(blank=True, max_length=200)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('oauth_state', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xero Connection',
            },
        ),
        migrations.CreateModel(
            name='XeroContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_contact_id', models.CharField(max_length=100, unique=True)),
                ('xero_contact_name', models.CharField(max_length=200)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_contact', to='core.owner')),
            ],
            options={
                'verbose_name': 'Xero Contact Mapping',
            },
        ),
        migrations.CreateModel(
            name='XeroInvoiceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_invoice_id', models.CharField(blank=True, max_length=100)),
                ('xero_invoice_number', models.CharField(blank=True, max_length=100)),
                ('sync_status', models.CharField(choices=[('not_pushed', 'Not Pushed'), ('pushed', 'Pushed to Xero'), ('paid_in_xero', 'Paid in Xero'), ('error', 'Error')], default='not_pushed', max_length=20)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_sync', to='core.invoice')),
            ],
            options={
                'verbose_name': 'Xero Invoice Sync',
            },
        ),
    ]
