# Generated by Django 5.2.12 on 2026-04-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoice_id_alter_invoicelineitem_id'),
        ('xero_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroinvoicesync',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_sync', to='invoicing.invoice'),
        ),
    ]
