# Generated by Django 5.2.17 on 2026-09-08 11:03

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xero_integration", "0002_alter_xeroinvoicesync_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xeroconnection",
            name="access_token",
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="xeroconnection",
            name="refresh_token",
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
