# Generated by Django 5.2.12 on 2026-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_extracharge_charge_type'),
        ('core', '0009_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extracharge',
            index=models.Index(fields=['invoiced', 'date'], name='charge_invoiced_date'),
        ),
        migrations.AddIndex(
            model_name='extracharge',
            index=models.Index(fields=['horse', 'invoiced'], name='charge_horse_invoiced'),
        ),
    ]
