# Generated by Django 5.2.12 on 2026-03-31 18:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_vet_fk_to_vaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='YardCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hay', 'Hay'), ('straw', 'Straw/Bedding'), ('feed', 'Feed'), ('supplements', 'Supplements'), ('staff', 'Staff/Wages'), ('rent', 'Rent/Lease'), ('fuel', 'Fuel'), ('utilities', 'Utilities'), ('repairs', 'Repairs/Maintenance'), ('insurance', 'Insurance'), ('equipment', 'Equipment'), ('professional', 'Professional Services'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/yard/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'category'], name='yardcost_date_category'), models.Index(fields=['is_recurring'], name='yardcost_recurring')],
            },
        ),
    ]
