# Generated by Django 5.2.12 on 2026-04-01 06:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_yardcost'),
        ('core', '0009_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_type', models.CharField(choices=[('hay', 'Hay'), ('haylage', 'Haylage'), ('hard_feed', 'Hard Feed'), ('supplements', 'Supplements'), ('other', 'Other')], max_length=20)),
                ('quantity', models.CharField(blank=True, help_text='e.g. 2 bales, 10kg, half a round bale', max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('is_recharged', models.BooleanField(default=False, help_text='Recharge this cost to horse owners in the field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_outs', to='core.location')),
                ('yard_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_outs', to='billing.yardcost')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='extracharge',
            name='feed_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_charges', to='billing.feedout'),
        ),
        migrations.AddIndex(
            model_name='feedout',
            index=models.Index(fields=['location', 'date'], name='feedout_location_date'),
        ),
    ]
