# Generated by Django 5.2.12 on 2026-04-04 14:28

import core.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_feedout_extracharge_feed_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedout',
            name='quantity_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric quantity for stock tracking', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedout',
            name='unit',
            field=models.CharField(blank=True, choices=[('bales', 'Bales'), ('bags', 'Bags'), ('kg', 'Kilograms'), ('tonnes', 'Tonnes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf']), core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='yardcost',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/yard/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf']), core.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('hay', 'Hay'), ('haylage', 'Haylage'), ('hard_feed', 'Hard Feed'), ('supplements', 'Supplements'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('bales', 'Bales'), ('bags', 'Bags'), ('kg', 'Kilograms'), ('tonnes', 'Tonnes')], max_length=20)),
                ('entry_type', models.CharField(choices=[('delivery', 'Delivery'), ('adjustment', 'Adjustment'), ('waste', 'Waste')], default='delivery', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['feed_type', 'date'], name='feedstock_type_date')],
            },
        ),
    ]
