# Generated by Django 5.2.12 on 2026-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_feedout_quantity_numeric_feedout_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedstock',
            name='site',
            field=models.CharField(blank=True, help_text='Which site is this stock stored at (e.g. Colgate, Somerford)', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedout',
            name='unit',
            field=models.CharField(blank=True, choices=[('small_bales', 'Small Bales'), ('large_bales', 'Large Bales'), ('round_bales', 'Round Bales'), ('large_square', 'Large Square Bales'), ('bags', 'Bags'), ('kg', 'Kilograms'), ('tonnes', 'Tonnes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedstock',
            name='unit',
            field=models.CharField(choices=[('small_bales', 'Small Bales'), ('large_bales', 'Large Bales'), ('round_bales', 'Round Bales'), ('large_square', 'Large Square Bales'), ('bags', 'Bags'), ('kg', 'Kilograms'), ('tonnes', 'Tonnes')], max_length=20),
        ),
    ]
