# Generated by Django 5.2.12 on 2026-04-04 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_feedstock_site_alter_feedout_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedout',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
