# Generated by Django 5.2.12 on 2026-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_feedout_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='yardcost',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Leave blank if the recurring cost has no end date', null=True),
        ),
    ]
