# Generated by Django 5.2.12 on 2026-04-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_recurrence_end_date'),
        ('invoicing', '0002_alter_invoice_id_alter_invoicelineitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracharge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_charges', to='invoicing.invoice'),
        ),
    ]
