# Generated by Django 5.2.15 on 2026-06-11 15:17

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_alter_extracharge_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracharge",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="receipts/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "pdf",
                            "heic",
                            "heif",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="yardcost",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="receipts/yard/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "pdf",
                            "heic",
                            "heif",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
