# Generated by Django 5.2.17 on 2026-09-07 18:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_alter_extracharge_receipt_image_and_more"),
        ("health", "0006_vaccination_cost_vaccination_extra_charge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("egg_count", "Worm egg count"),
                            ("worming", "Wormer"),
                            ("farrier", "Farrier"),
                            ("vet", "Vet"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Decides which record forms offer this service.",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Charged per horse. Can be overridden when recording.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "farrier_work",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "— not set —"),
                            ("trim", "Trim Only"),
                            ("front_shoes", "Front Shoes"),
                            ("full_set", "Full Set"),
                            ("remedial", "Remedial Work"),
                            ("remove", "Shoe Removal"),
                        ],
                        help_text="Farrier items only: the work type the visit is recorded as.",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vaccination_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vaccination items only: the type the record is filed under.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_items",
                        to="health.vaccinationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "sort_order", "name"],
            },
        ),
    ]
