# Generated by Django 5.2.13 on 2026-04-22 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_businesssettings_next_run_number"),
        ("invoicing", "0002_alter_invoice_id_alter_invoicelineitem_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="horse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core.horse",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_number", models.PositiveIntegerField(unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("concatenate_invoices", models.BooleanField(default=True)),
                ("next_sub_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-run_number"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoicing.invoicerun",
            ),
        ),
    ]
