# Generated by Django 5.2.13 on 2026-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0002_alter_invoice_id_alter_invoicelineitem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="last_overdue_reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
