# Generated by Django 5.2.16 on 2026-07-13 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=4
            ),
        ),
    ]
