# Generated by Django 5.2.17 on 2026-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0005_invoice_vat_amount_invoice_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="send_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="send_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
