/*
  Lists every placeholder and every missing photograph in the content, and
  writes PLACEHOLDERS.md and IMAGES-NEEDED.md. Run with `npm run placeholders`
  after editing content, so the lists stay true.

  A placeholder is [[TODO: what | owner: who | ref: where]] anywhere in
  src/content. A missing photograph is an image with no `src`.
*/
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const contentDir = join(root, 'src/content');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const TODO = /\[\[TODO:([^\]]*)\]\]/g;

function parseTodo(body) {
  const parts = body.split('|').map((s) => s.trim());
  const what = parts[0] ?? '';
  const owner = (parts.find((p) => p.startsWith('owner:')) ?? 'owner:').slice(6).trim();
  const ref = (parts.find((p) => p.startsWith('ref:')) ?? 'ref:').slice(4).trim();
  return { what, owner: owner || 'unknown', ref: ref || 'unknown' };
}

/* Images in JSON: any object with `alt` and no `src`. */
function imagesInJson(value, path, out, file) {
  if (Array.isArray(value)) {
    value.forEach((v, i) => imagesInJson(v, `${path}[${i + 1}]`, out, file));
  } else if (value && typeof value === 'object') {
    if ('alt' in value && !('src' in value)) {
      out.push({
        brief: value.brief ?? '',
        owner: value.owner ?? 'unknown',
        aspect: value.aspect ?? 'landscape',
        where: `${file} ${path}`,
      });
    }
    for (const [k, v] of Object.entries(value)) imagesInJson(v, path ? `${path}.${k}` : k, out, file);
  }
}

/* Images in Markdown front matter: a `brief:` line, with `owner:`, `src:` and
   `aspect:` in the lines around it at the same indentation. */
function imagesInFrontMatter(text, out, file) {
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return;
  const lines = match[1].split('\n');
  lines.forEach((line, i) => {
    const m = line.match(/^(\s*)brief:\s*(.*)$/);
    if (!m) return;
    const indent = m[1].length;
    const block = {};
    for (let j = Math.max(0, i - 6); j < Math.min(lines.length, i + 6); j++) {
      const l = lines[j].match(/^(\s*)(alt|owner|src|aspect):\s*(.*)$/);
      if (l && l[1].length === indent) block[l[2]] = l[3].replace(/^"|"$/g, '');
    }
    if (block.src) return;
    let parent = 'image';
    for (let j = i - 1; j >= 0; j--) {
      const p = lines[j].match(/^(\s*)([\w-]+):\s*$/);
      if (p && p[1].length < indent) { parent = p[2]; break; }
    }
    out.push({
      brief: m[2].replace(/^"|"$/g, ''),
      owner: block.owner ?? 'unknown',
      aspect: block.aspect ?? 'landscape',
      where: `${file} ${parent}`,
    });
  });
}

const todos = [];
const images = [];

for (const file of walk(contentDir).filter((f) => /\.(json|md)$/.test(f))) {
  const rel = relative(root, file);
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(TODO)) todos.push({ ...parseTodo(m[1]), file: rel });
  if (file.endsWith('.json')) imagesInJson(JSON.parse(text), '', images, rel);
  else imagesInFrontMatter(text, images, rel);
}

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const owners = [...new Set([...todos.map((t) => t.owner), ...images.map((i) => i.owner)])].sort();

let md = `# Placeholders

Every fact the site still needs. Generated by \`npm run placeholders\` from
the content files; do not edit by hand. Each one shows on the page as
\`[[TODO: what | owner: who | ref: where]]\` until it is replaced.

Total: ${todos.length} placeholders, ${images.length} photographs (see IMAGES-NEEDED.md).

`;
for (const owner of owners) {
  const mine = todos.filter((t) => t.owner === owner);
  if (!mine.length) continue;
  md += `## Owner: ${owner} (${mine.length})\n\n| What is needed | Where it belongs | File |\n|---|---|---|\n`;
  for (const t of mine) md += `| ${cell(t.what)} | ${cell(t.ref)} | \`${t.file}\` |\n`;
  md += '\n';
}
/* Placeholders the code itself adds, for things content cannot hold (an image
   with no file, a form with no address to post to). */
const codeTodos = [];
for (const file of walk(join(root, 'src/components')).filter((f) => f.endsWith('.astro'))) {
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(/\[\[TODO:(.*?)\]\]/g)) {
    codeTodos.push({ text: m[1].replace(/\$\{[^}]*\}/g, '...').trim(), file: relative(root, file) });
  }
}
if (codeTodos.length) {
  md += `## Added by the code\n\nThese appear wherever the condition holds. They are not in a content file.\n\n| Placeholder | Component |\n|---|---|\n`;
  for (const t of codeTodos) md += `| ${cell(t.text)} | \`${t.file}\` |\n`;
  md += '\n';
}

writeFileSync(join(root, 'PLACEHOLDERS.md'), md);

let im = `# Photographs needed

Every place on the site that is waiting for a photograph. Generated by
\`npm run placeholders\`; do not edit by hand. Each one shows on the page as a
grey block carrying its brief until the file exists.

No stock, external or generated images. Real photographs of the farm, its
animals and its people, taken in good light.

| Shape | Minimum size | Used for |
|---|---|---|
| wide (16:9) | 2400 px wide | The banner and page tops |
| landscape (3:2) | 1600 px wide | Shelves, image and text blocks, galleries |
| portrait (4:5) | 1200 px wide | People |
| square (1:1) | 1200 px wide | Small pictures |

To add one: put the file in \`public/images/\`, then set \`src\` on the image in
the content file, for example \`"src": "/images/yard-march.jpg"\`. Keep \`alt\`
true to the photograph. See CONTENT.md.

Total: ${images.length}.

`;
for (const owner of owners) {
  const mine = images.filter((i) => i.owner === owner);
  if (!mine.length) continue;
  im += `## Owner: ${owner} (${mine.length})\n\n| Brief | Shape | Where |\n|---|---|---|\n`;
  for (const i of mine) im += `| ${cell(i.brief)} | ${i.aspect} | \`${cell(i.where)}\` |\n`;
  im += '\n';
}
writeFileSync(join(root, 'IMAGES-NEEDED.md'), im);

console.log(`${todos.length} placeholders, ${images.length} photographs. Wrote PLACEHOLDERS.md and IMAGES-NEEDED.md.`);
