# Generated by Django 5.2.12 on 2026-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_vet_fk_to_vaccination'),
        ('core', '0009_alter_invoice_due_date_and_more'),
        ('health', '0004_vaccination_add_vet_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farriervisit',
            index=models.Index(fields=['horse', 'next_due_date'], name='farrier_horse_nextdue'),
        ),
        migrations.AddIndex(
            model_name='farriervisit',
            index=models.Index(fields=['next_due_date'], name='farrier_nextdue'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['horse', 'next_due_date'], name='vax_horse_nextdue'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['next_due_date'], name='vax_nextdue'),
        ),
        migrations.AddIndex(
            model_name='vetvisit',
            index=models.Index(fields=['horse', 'follow_up_date'], name='vet_horse_followup'),
        ),
        migrations.AddIndex(
            model_name='wormeggcount',
            index=models.Index(fields=['horse', 'date'], name='egg_horse_date'),
        ),
    ]
