# Generated by Django 5.2.16 on 2026-07-15 08:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_alter_extracharge_receipt_image_and_more"),
        ("health", "0005_add_vet_fk_to_vaccination"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Leave 0 if not billable; a cost creates a charge for the owner",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="vaccination",
            name="extra_charge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vaccination",
                to="billing.extracharge",
            ),
        ),
        migrations.AddField(
            model_name="wormingtreatment",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Leave 0 if not billable; a cost creates a charge for the owner",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="wormingtreatment",
            name="extra_charge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worming_treatment",
                to="billing.extracharge",
            ),
        ),
    ]
