# Generated by Django 5.2.17 on 2026-09-07 18:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_service_items"),
        ("health", "0006_vaccination_cost_vaccination_extra_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wormeggcount",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Leave 0 if not billable; a cost creates a charge for the owner",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="wormeggcount",
            name="extra_charge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worm_egg_count",
                to="billing.extracharge",
            ),
        ),
    ]
