# Generated by Django 5.2.17 on 2026-09-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_seed_service_items"),
        ("health", "0007_service_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedingrecord",
            name="breeding_reminders_sent",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keys of owner reminders already sent (scan14, heartbeat, foal30, foal7)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="breedingrecord",
            name="due_date_is_manual",
            field=models.BooleanField(
                default=False,
                help_text="True when the foal due date was typed in rather than worked out as 340 days from the last covering.",
            ),
        ),
        migrations.CreateModel(
            name="Covering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("natural", "Natural cover"),
                            ("ai_fresh", "AI — fresh"),
                            ("ai_chilled", "AI — chilled"),
                            ("ai_frozen", "AI — frozen"),
                            ("", "Not recorded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stallion_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank when it is the record's stallion",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverings",
                        to="health.breedingrecord",
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverings",
                        to="billing.serviceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PregnancyScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("14_day", "14-day scan"),
                            ("heartbeat", "Heartbeat scan"),
                            ("sex", "Sexing scan"),
                            ("other", "Other scan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("in_foal", "In foal"),
                            ("not_in_foal", "Not in foal"),
                            ("twins", "Twins"),
                            ("inconclusive", "Inconclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="health.breedingrecord",
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pregnancy_scans",
                        to="billing.serviceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "pk"],
            },
        ),
    ]
