# Generated by Django 5.2.17 on 2026-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0009_backfill_coverings_and_scans"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedingrecord",
            name="foaling_watch",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Foaling-watch checklist: {"items": {key: true}, "notes": ""}',
            ),
        ),
    ]
