# Generated by Django 5.2.17 on 2026-09-08 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0010_foaling_watch"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedingrecord",
            name="weaned_date",
            field=models.DateField(
                blank=True,
                help_text="When the foal was weaned (split from the mare)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="breedingrecord",
            name="weaning_notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="FoalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foal_notes",
                        to="health.breedingrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
