# Generated by Django 5.2.17 on 2026-09-10 07:54

from datetime import timedelta

from django.db import migrations, models

WORMING_INTERVAL = timedelta(weeks=13)


def backfill_due_dates(apps, schema_editor):
    """Give every existing dose the same due date a new one would get.

    Without this the horse list's Credentials block reads "Not recorded"
    for every horse until the next dose is logged, which looks like data
    loss rather than a new field.
    """
    WormingTreatment = apps.get_model('health', 'WormingTreatment')
    rows = []
    for treatment in WormingTreatment.objects.filter(next_due_date__isnull=True):
        treatment.next_due_date = treatment.date + WORMING_INTERVAL
        rows.append(treatment)
    WormingTreatment.objects.bulk_update(rows, ['next_due_date'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_seed_service_items"),
        ("core", "0037_horse_microchip"),
        ("health", "0011_foal_weaning_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="wormingtreatment",
            name="next_due_date",
            field=models.DateField(
                blank=True,
                help_text="Left blank, this is set to 13 weeks after the dose",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_due_dates, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="wormingtreatment",
            index=models.Index(
                fields=["horse", "next_due_date"], name="worming_horse_nextdue"
            ),
        ),
        migrations.AddIndex(
            model_name="wormingtreatment",
            index=models.Index(fields=["next_due_date"], name="worming_nextdue"),
        ),
    ]
