# Generated by Django 5.2.18 on 2026-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0012_wormingtreatment_next_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="course_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary_1", "Primary course: 1st (V1)"),
                    ("primary_2", "Primary course: 2nd (V2)"),
                    ("first_booster", "1st booster (V3)"),
                    ("booster", "Booster"),
                ],
                help_text="Sets the reminder window for the next dose. Leave blank to use the type's interval.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vaccination",
            name="due_from",
            field=models.DateField(
                blank=True,
                help_text="Earliest date for the next dose (set from the course stage)",
                null=True,
            ),
        ),
    ]
